# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(409, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fr_content = QtWidgets.QFrame(Dialog)
        self.fr_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_content.setObjectName("fr_content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fr_content)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fr_picture = QtWidgets.QFrame(self.fr_content)
        self.fr_picture.setAutoFillBackground(False)
        self.fr_picture.setStyleSheet("background-color: rgb(151, 158, 157);")
        self.fr_picture.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_picture.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_picture.setObjectName("fr_picture")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fr_picture)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_picture = QtWidgets.QLabel(self.fr_picture)
        self.label_picture.setAlignment(QtCore.Qt.AlignCenter)
        self.label_picture.setObjectName("label_picture")
        self.verticalLayout_2.addWidget(self.label_picture)
        self.horizontalLayout.addWidget(self.fr_picture)
        self.fr_log = QtWidgets.QFrame(self.fr_content)
        self.fr_log.setMaximumSize(QtCore.QSize(120, 16777215))
        self.fr_log.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_log.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_log.setObjectName("fr_log")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fr_log)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.fr_log)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_2.addWidget(self.plainTextEdit)
        self.horizontalLayout.addWidget(self.fr_log)
        self.verticalLayout.addWidget(self.fr_content)
        self.fr_submit = QtWidgets.QFrame(Dialog)
        self.fr_submit.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_submit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_submit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_submit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_submit.setObjectName("fr_submit")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fr_submit)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.fr_submit)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_time = QtWidgets.QLabel(self.frame_2)
        self.label_time.setMinimumSize(QtCore.QSize(0, 0))
        self.label_time.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("QLabel{\n"
"color: rgb(50, 120, 60);\n"
"}\n"
"QLabel:hover{\n"
"color: rgba(8, 255, 206,150);\n"
"}\n"
"\n"
"")
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.verticalLayout_3.addWidget(self.label_time)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.lineEdit = QtWidgets.QLineEdit(self.fr_submit)
        self.lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("VNI-Vari")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setMaxLength(2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.frame = QtWidgets.QFrame(self.fr_submit)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3.addWidget(self.frame)
        self.comboBox = QtWidgets.QComboBox(self.fr_submit)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.fr_submit)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_picture.setText(_translate("Dialog", "Picture"))
        self.label_time.setText(_translate("Dialog", "TIME"))
        self.comboBox.setCurrentText(_translate("Dialog", "Type"))
